#!/bin/bash

# serena Installation Script for Debian Linux
# Generated by Gearbox Script Generator - Python Template
# Automated clone, dependency installation, configuration, build, and install
# Usage: ./install-serena.sh [OPTIONS]

set -e  # Exit on any error

# Find the script directory and load common library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$(dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")")"

# Source common library for shared functions
if [[ -f "$REPO_DIR/scripts/lib/common.sh" ]]; then
    source "$REPO_DIR/scripts/lib/common.sh"
else
    echo "ERROR: common.sh not found in $REPO_DIR/scripts/lib/" >&2
    exit 1
fi

# Configuration
SERENA_DIR="serena"
SERENA_REPO="https://github.com/huggingface/serena.git"
PYTHON_MIN_VERSION="3.11.0"

# Default options
BUILD_TYPE="standard"
MODE="install"         # config, build, install
SKIP_DEPS=false
RUN_TESTS=false
FORCE_INSTALL=false
USE_VENV=true

# Show help
show_help() {
    cat << EOF
Coding agent toolkit (Python)

Usage: $0 [OPTIONS]

Build Types:
  -f                   maximum build
  -m                   minimal build
  -s                   standard build

Modes:
  -c, --config-only     Configure only (prepare build)
  -b, --build-only      Configure and build (no install)
  -i, --install         Configure, build, and install (default)

Options:
  --skip-deps          Skip dependency installation
  --run-tests          Run test suite after building
  --force              Force reinstallation if already installed
  --no-venv            Install globally instead of in virtual environment
  -h, --help           Show this help message

Examples:
  $0                   # Default build and install
  $0 -m -c             # Minimal build, config only
  $0 -f --run-tests    # Full build with tests

EOF
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -f)
            BUILD_TYPE="maximum"
            shift
            ;;
        -m)
            BUILD_TYPE="minimal"
            shift
            ;;
        -s)
            BUILD_TYPE="standard"
            shift
            ;;
        -c|--config-only)
            MODE="config"
            shift
            ;;
        -b|--build-only)
            MODE="build"
            shift
            ;;
        -i|--install)
            MODE="install"
            shift
            ;;
        --skip-deps)
            SKIP_DEPS=true
            shift
            ;;
        --run-tests)
            RUN_TESTS=true
            shift
            ;;
        --force)
            FORCE_INSTALL=true
            shift
            ;;
        --no-venv)
            USE_VENV=false
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Version comparison function
version_compare() {
    if [[ $1 == $2 ]]; then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++)); do
        if [[ -z ${ver2[i]} ]]; then
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]})); then
            return 0
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]})); then
            return 1
        fi
    done
    return 0
}

# Check and install Python
install_python() {
    if command -v python3 &> /dev/null; then
        local current_version=$(python3 --version | cut -d' ' -f2)
        log "Found Python version: $current_version"
        
        if version_compare $current_version $PYTHON_MIN_VERSION; then
            log "Python version is sufficient (>= $PYTHON_MIN_VERSION)"
            return 0
        else
            warning "Python version $current_version is below minimum required $PYTHON_MIN_VERSION"
        fi
    fi
    
    log "Installing Python development packages..."
    sudo apt install -y \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        python3-wheel \
        python3-setuptools \
        || error "Failed to install Python packages"
    
    success "Python installed successfully"
}

# Get pip install options based on build type
get_pip_install_options() {
    local options=""
    
    case $BUILD_TYPE in
        debug|minimal)
            options="--no-deps --no-cache-dir"
            ;;
        release|standard)
            options="--no-cache-dir"
            ;;
        optimized|maximum)
            options="--no-cache-dir --compile"
            ;;
    esac
    
    if [[ "$FORCE_INSTALL" == true ]]; then
        options="$options --force-reinstall"
    fi
    
    if [[ "$USE_VENV" == false ]]; then
        options="$options --break-system-packages"
    fi
    
    echo "$options"
}

# Install dependencies
install_dependencies() {
    if [[ "$SKIP_DEPS" == true ]]; then
        log "Skipping dependency installation as requested"
        return 0
    fi

    # Update package list
    log "Updating package list..."
    sudo apt update || error "Failed to update package list"

    # Install basic build tools
    log "Installing build tools..."
    sudo apt install -y \
        build-essential \
        git \
        curl \
        wget \
        pkg-config \
        || error "Failed to install build tools"


    # Install Python
    install_python

    success "Dependencies installed successfully"
}

# Setup virtual environment
setup_venv() {
    if [[ "$USE_VENV" == false ]]; then
        log "Skipping virtual environment setup"
        return 0
    fi
    
    local venv_dir="serena-venv"
    
    if [[ -d "$venv_dir" ]]; then
        log "Found existing virtual environment: $venv_dir"
        source "$venv_dir/bin/activate" || error "Failed to activate virtual environment"
    else
        log "Creating virtual environment: $venv_dir"
        python3 -m venv "$venv_dir" || error "Failed to create virtual environment"
        source "$venv_dir/bin/activate" || error "Failed to activate virtual environment"
        
        # Upgrade pip in virtual environment (critical for package compatibility)
        log "Upgrading pip, setuptools, and wheel for reliable package installation..."
        pip install --upgrade pip setuptools wheel || error "Failed to upgrade pip tools - this may cause package installation failures. Check network connectivity and pip configuration."
    fi
    
    success "Virtual environment activated"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then
   error "This script should not be run as root for security reasons"
fi

log "Starting serena $MODE process for Debian Linux"
log "Build type: $BUILD_TYPE"
log "Mode: $MODE"
log "Use virtual environment: $USE_VENV"

# Handle serena source code
if [[ -d "$SERENA_DIR" ]]; then
    log "Found existing serena directory: $SERENA_DIR"
    
    # Check if it's a git repository
    if [[ -d "$SERENA_DIR/.git" ]]; then
        log "Existing directory is a git repository"
        
        # Check if it's the correct repository
        cd "$SERENA_DIR"
        CURRENT_ORIGIN=$(git remote get-url origin 2>/dev/null || echo "")
        
        if [[ "$CURRENT_ORIGIN" == "$SERENA_REPO" ]]; then
            log "Repository origin matches expected serena repository"
            
            log "Pulling latest changes..."
            git pull origin main || git pull origin master || warning "Failed to pull latest changes"
            success "Repository updated successfully"
        else
            warning "Existing git repository has different origin: $CURRENT_ORIGIN"
            cd ..
            rm -rf "$SERENA_DIR"
            log "Cloning serena repository..."
            git clone "$SERENA_REPO" "$SERENA_DIR" || error "Failed to clone serena repository"
            cd "$SERENA_DIR"
            success "serena repository cloned successfully"
        fi
        cd ..
    else
        warning "Directory exists but is not a git repository"
        rm -rf "$SERENA_DIR"
        log "Cloning serena repository..."
        git clone "$SERENA_REPO" "$SERENA_DIR" || error "Failed to clone serena repository"
        success "serena repository cloned successfully"
    fi
else
    log "Cloning serena repository..."
    git clone "$SERENA_REPO" "$SERENA_DIR" || error "Failed to clone serena repository"
    success "serena repository cloned successfully"
fi

# Change to serena directory
cd "$SERENA_DIR"

# Verify we're in the correct directory
if [[ ! -f "setup.py" && ! -f "pyproject.toml" && ! -f "requirements.txt" ]]; then
    error "Invalid serena source directory - missing Python project files"
fi

# Install dependencies
install_dependencies

# Setup virtual environment
setup_venv

# Get build configuration
PIP_INSTALL_OPTIONS=$(get_pip_install_options)

log "Configuring serena with $BUILD_TYPE settings..."
log "Pip install options: $PIP_INSTALL_OPTIONS"
log "Virtual environment: $USE_VENV"

success "Configuration completed successfully"

# Exit if config-only mode
if [[ "$MODE" == "config" ]]; then
    success "Configuration completed. Run with --build-only or --install to continue."
    success "Install command would be: pip install $PIP_INSTALL_OPTIONS ."
    exit 0
fi

# Build serena (for Python, this is mainly installing dependencies)
log "Installing serena dependencies and building..."

# Install project dependencies
if [[ -f "requirements.txt" ]]; then
    log "Installing requirements.txt dependencies..."
    pip install $PIP_INSTALL_OPTIONS -r requirements.txt || error "Failed to install dependencies"
fi

if [[ -f "setup.py" ]]; then
    log "Building with setup.py..."
    python setup.py build || error "Failed to build serena"
elif [[ -f "pyproject.toml" ]]; then
    log "Building with pyproject.toml..."
    pip install $PIP_INSTALL_OPTIONS build || error "Failed to install build tool"
    python -m build || error "Failed to build serena"
fi

success "Build completed successfully"

# Run tests if requested
if [[ "$RUN_TESTS" == true ]]; then
    log "Running test suite..."
    if [[ -f "pytest.ini" || -f "setup.cfg" ]] || command -v pytest &> /dev/null; then
        pytest || warning "Some tests failed, but continuing"
    elif [[ -f "test_*.py" ]] || find . -name "test_*.py" -type f | grep -q .; then
        python -m unittest discover || warning "Some tests failed, but continuing"
    else
        warning "No test framework found, skipping tests"
    fi
    success "Test suite completed"
fi

# Exit if build-only mode
if [[ "$MODE" == "build" ]]; then
    success "Build completed. Run with --install to install the package."
    exit 0
fi

# Install serena
log "Installing serena..."

# Check if we can use cached installation
if is_cached "serena" "$BUILD_TYPE"; then
    log "Found cached serena build, checking if installation is needed..."
    # For Python tools, we typically check if the command is available
    if command -v serena &> /dev/null && [[ "$FORCE_INSTALL" == false ]]; then
        success "serena already installed and cached"
    else
        warning "Cached version not available or force install requested"
        # Install the package
        if [[ -f "setup.py" ]]; then
            pip install $PIP_INSTALL_OPTIONS . || error "Failed to install serena"
        elif [[ -f "pyproject.toml" ]]; then
            pip install $PIP_INSTALL_OPTIONS . || error "Failed to install serena"
        else
            pip install $PIP_INSTALL_OPTIONS https://github.com/huggingface/serena.git || error "Failed to install serena"
        fi
        
        # Cache the installation
        cache_build "serena" "$BUILD_TYPE" "$(which serena 2>/dev/null || echo 'installed')"
    fi
else
    # Install the package
    if [[ -f "setup.py" ]]; then
        pip install $PIP_INSTALL_OPTIONS . || error "Failed to install serena"
    elif [[ -f "pyproject.toml" ]]; then
        pip install $PIP_INSTALL_OPTIONS . || error "Failed to install serena"
    else
        pip install $PIP_INSTALL_OPTIONS https://github.com/huggingface/serena.git || error "Failed to install serena"
    fi
    
    # Cache the installation
    cache_build "serena" "$BUILD_TYPE" "$(which serena 2>/dev/null || echo 'installed')"
fi

# Create system-wide wrapper if using virtual environment
if [[ "$USE_VENV" == true ]]; then
    local venv_dir="serena-venv"
    local venv_binary="$PWD/$venv_dir/bin/serena"
    
    if [[ -f "$venv_binary" ]]; then
        log "Creating system-wide wrapper script..."
        
        # Create wrapper script
        sudo tee /usr/local/bin/serena > /dev/null << EOF
#!/bin/bash
# serena wrapper script - generated by gearbox
exec "$venv_binary" "\$@"
EOF
        
        sudo chmod +x /usr/local/bin/serena
        success "System-wide wrapper created"
    else
        warning "Virtual environment binary not found, serena may not be available system-wide"
    fi
fi

# Verify installation
log "Verifying installation..."
# Update PATH to include install location
export PATH="/usr/local/bin:$PATH"
# Clear bash command hash table
hash -r

if command -v serena &> /dev/null; then
    success "serena installation verified!"
    echo
    log "serena version information:"
    serena serena --version || echo "Version command not available"
    echo
    log "Build type: $BUILD_TYPE"
    log "Virtual environment: $USE_VENV"
    case $BUILD_TYPE in
        debug|minimal)
            log "Features: Minimal installation with basic dependencies"
            ;;
        release|standard)
            log "Features: Standard installation with full dependencies"
            ;;
        optimized|maximum)
            log "Features: Optimized installation with compiled bytecode"
            ;;
    esac
    echo
    success "serena installation completed successfully!"
    log "You can now use the 'serena' command"
    echo
    log "Installation paths:"
    if [[ "$USE_VENV" == true ]]; then
        log "  Virtual env: $(pwd)/serena-venv"
        log "  Wrapper: /usr/local/bin/serena"
    else
        log "  serena: $(which serena)"
    fi
    echo
    log "Script completed in directory: $(pwd)"
else
    error "serena installation verification failed - command not found in PATH"
fi